twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    paths:
        '%kernel.project_dir%/templates/dashboard': 'Dashboard'
        '%kernel.project_dir%/templates/emails': 'Email'
        '%kernel.project_dir%/templates/client': 'ClientEntity'
        '%kernel.project_dir%/templates/project': 'Project'